export enum TypeBadge {
    BIENVENUE = 'BIENVENUE',
    DONATEUR_BARAKA = 'DONATEUR_BARAKA',
    SAVEUR_ALIMENTAIRE = 'SAVEUR_ALIMENTAIRE',
    VOISIN_DE_CONFIANCE = 'VOISIN_DE_CONFIANCE',
    AMBASSADEUR_LOCAL = 'AMBASSADEUR_LOCAL',
    GARANT_SOLIDAIRE = 'GARANT_SOLIDAIRE',
    CHAMPION_ECO = 'CHAMPION_ECO',
}