version: '3.8'

services:
  # Base de données PostgreSQL (Utilisateurs, Annonces, Transactions, Wallet)
  postgres:
    image: postgres:15-alpine
    container_name: lbaraka_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lbaraka
      POSTGRES_DB: lbaraka
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Base de données MongoDB (Chat messages)
  mongo:
    image: mongo:5.0
    container_name: lbaraka_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Interface pour MongoDB
  mongo-express:
    image: mongo-express
    container_name: lbaraka_mongo_express
    restart: unless-stopped
    ports:
      - "8981:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      - mongo

  # Cache Redis (Requirements)
  redis:
    image: redis:7-alpine
    container_name: lbaraka_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  # Stockage MinIO (S3 Compatible pour Photos et Contrats PDF)
  minio:
    image: minio/minio:latest
    container_name: lbaraka_minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: lbaraka
      MINIO_ROOT_PASSWORD: lbaraka123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  # Backend NestJS (Hot Reload)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lbaraka_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:lbaraka@postgres:5432/lbaraka?schema=public
      - MONGODB_URL=mongodb://mongo:27017/lbaraka
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_USE_SSL=false
      - MINIO_ACCESS_KEY=lbaraka
      - MINIO_SECRET_KEY=lbaraka123
      - MINIO_BUCKET=lbaraka-annonces
      - MINIO_PUBLIC_URL=http://10.90.27.250:9000
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres
      - mongo
      - redis
      - minio

volumes:
  postgres_data:
  mongo_data:
  minio_data:
